# Generated by Django 5.2.4 on 2026-04-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_allergies_patientprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
