# Generated by Django 5.2.4 on 2026-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='provider_facility',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='report_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
