# Generated by Django 5.2.4 on 2026-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medicalrecord_provider_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='report_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
