# Generated by Django 5.2.4 on 2026-04-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_facility_reportcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='visible_to_patient',
            field=models.BooleanField(default=True),
        ),
    ]
