# Generated by Django 5.2.4 on 2026-05-01 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_medication_notification_medicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='medical.facility'),
        ),
    ]
